rules:
  - id: python-hardcoded-credentials
    languages: [python]
    patterns:
      - pattern: "password = '...'"
    message: "Hard-coded password found"
    severity: ERROR

  - id: js-hardcoded-credential
    languages: [javascript, typescript]
    patterns:
      - pattern: "const password = '...'"
    message: "Hard-coded password found"
    severity: ERROR
